export const flags = [
	{ name: "United States", code: "us" },
	{ name: "Canada", code: "ca" },
	{ name: "Mexico", code: "mx" },
	{ name: "Greenland", code: "gl" },
	{ name: "Panama", code: "pa" },
	{ name: "Costa Rica", code: "cr" },
	{ name: "Guatemala", code: "gt" },
	{ name: "Honduras", code: "hn" },
	{ name: "El Salvador", code: "sv" },
	{ name: "Nicaragua", code: "ni" },
	{ name: "Belize", code: "bz" },
	{ name: "Jamaica", code: "jm" },
	{ name: "Cuba", code: "cu" },
	{ name: "Dominican Republic", code: "do" },
	{ name: "Haiti", code: "ht" },
	{ name: "Bahamas", code: "bs" },
	{ name: "Barbados", code: "bb" },
	{ name: "Trinidad and Tobago", code: "tt" },
	{ name: "Saint Lucia", code: "lc" },
	{ name: "Grenada", code: "gd" },
	{ name: "Antigua and Barbuda", code: "ag" },
	{ name: "Dominica", code: "dm" },
	{ name: "Saint Kitts and Nevis", code: "kn" },
	{ name: "Saint Vincent and the Grenadines", code: "vc" },
	{ name: "Puerto Rico", code: "pr" },
	{ name: "Cayman Islands", code: "ky" },
	{ name: "Turks and Caicos Islands", code: "tc" },
	{ name: "British Virgin Islands", code: "vg" },
	{ name: "US Virgin Islands", code: "vi" },
	{ name: "Anguilla", code: "ai" },
	{ name: "Montserrat", code: "ms" },
	{ name: "Martinique", code: "mq" },
	{ name: "Guadeloupe", code: "gp" },
	{ name: "Saint Martin", code: "mf" },
	{ name: "Aruba", code: "aw" },
	{ name: "Curaçao", code: "cw" },
	{ name: "Bonaire", code: "bq" },
	{ name: "Brazil", code: "br" },
	{ name: "Argentina", code: "ar" },
	{ name: "Chile", code: "cl" },
	{ name: "Colombia", code: "co" },
	{ name: "Peru", code: "pe" },
	{ name: "Venezuela", code: "ve" },
	{ name: "Ecuador", code: "ec" },
	{ name: "Bolivia", code: "bo" },
	{ name: "Paraguay", code: "py" },
	{ name: "Uruguay", code: "uy" },
	{ name: "Guyana", code: "gy" },
	{ name: "Suriname", code: "sr" },
	{ name: "French Guiana", code: "gf" },
	{ name: "Falkland Islands", code: "fk" },
	{ name: "United Kingdom", code: "gb" },
	{ name: "Germany", code: "de" },
	{ name: "France", code: "fr" },
	{ name: "Italy", code: "it" },
	{ name: "Spain", code: "es" },
	{ name: "Portugal", code: "pt" },
	{ name: "Netherlands", code: "nl" },
	{ name: "Belgium", code: "be" },
	{ name: "Switzerland", code: "ch" },
	{ name: "Austria", code: "at" },
	{ name: "Sweden", code: "se" },
	{ name: "Norway", code: "no" },
	{ name: "Denmark", code: "dk" },
	{ name: "Finland", code: "fi" },
	{ name: "Iceland", code: "is" },
	{ name: "Ireland", code: "ie" },
	{ name: "Greece", code: "gr" },
	{ name: "Poland", code: "pl" },
	{ name: "Ukraine", code: "ua" },
	{ name: "Czech Republic", code: "cz" },
	{ name: "Slovakia", code: "sk" },
	{ name: "Hungary", code: "hu" },
	{ name: "Romania", code: "ro" },
	{ name: "Bulgaria", code: "bg" },
	{ name: "Croatia", code: "hr" },
	{ name: "Serbia", code: "rs" },
	{ name: "Bosnia and Herzegovina", code: "ba" },
	{ name: "Slovenia", code: "si" },
	{ name: "Albania", code: "al" },
	{ name: "North Macedonia", code: "mk" },
	{ name: "Montenegro", code: "me" },
	{ name: "Kosovo", code: "xk" },
	{ name: "Estonia", code: "ee" },
	{ name: "Latvia", code: "lv" },
	{ name: "Lithuania", code: "lt" },
	{ name: "Moldova", code: "md" },
	{ name: "Belarus", code: "by" },
	{ name: "Russia", code: "ru" },
	{ name: "Malta", code: "mt" },
	{ name: "Cyprus", code: "cy" },
	{ name: "Luxembourg", code: "lu" },
	{ name: "Liechtenstein", code: "li" },
	{ name: "San Marino", code: "sm" },
	{ name: "Monaco", code: "mc" },
	{ name: "Andorra", code: "ad" },
	{ name: "Vatican City", code: "va" },
	{ name: "Faroe Islands", code: "fo" },
	{ name: "Japan", code: "jp" },
	{ name: "China", code: "cn" },
	{ name: "India", code: "in" },
	{ name: "South Korea", code: "kr" },
	{ name: "North Korea", code: "kp" },
	{ name: "Indonesia", code: "id" },
	{ name: "Thailand", code: "th" },
	{ name: "Vietnam", code: "vn" },
	{ name: "Philippines", code: "ph" },
	{ name: "Malaysia", code: "my" },
	{ name: "Singapore", code: "sg" },
	{ name: "Cambodia", code: "kh" },
	{ name: "Laos", code: "la" },
	{ name: "Myanmar", code: "mm" },
	{ name: "Bangladesh", code: "bd" },
	{ name: "Pakistan", code: "pk" },
	{ name: "Sri Lanka", code: "lk" },
	{ name: "Nepal", code: "np" },
	{ name: "Bhutan", code: "bt" },
	{ name: "Maldives", code: "mv" },
	{ name: "Mongolia", code: "mn" },
	{ name: "Kazakhstan", code: "kz" },
	{ name: "Uzbekistan", code: "uz" },
	{ name: "Turkmenistan", code: "tm" },
	{ name: "Kyrgyzstan", code: "kg" },
	{ name: "Tajikistan", code: "tj" },
	{ name: "Afghanistan", code: "af" },
	{ name: "Turkey", code: "tr" },
	{ name: "Saudi Arabia", code: "sa" },
	{ name: "United Arab Emirates", code: "ae" },
	{ name: "Israel", code: "il" },
	{ name: "Iran", code: "ir" },
	{ name: "Iraq", code: "iq" },
	{ name: "Syria", code: "sy" },
	{ name: "Jordan", code: "jo" },
	{ name: "Lebanon", code: "lb" },
	{ name: "Kuwait", code: "kw" },
	{ name: "Qatar", code: "qa" },
	{ name: "Bahrain", code: "bh" },
	{ name: "Oman", code: "om" },
	{ name: "Yemen", code: "ye" },
	{ name: "Azerbaijan", code: "az" },
	{ name: "Armenia", code: "am" },
	{ name: "Georgia", code: "ge" },
	{ name: "Taiwan", code: "tw" },
	{ name: "Hong Kong", code: "hk" },
	{ name: "Palestine", code: "ps" },
	{ name: "Brunei", code: "bn" },
	{ name: "Timor-Leste", code: "tl" },
	{ name: "South Africa", code: "za" },
	{ name: "Nigeria", code: "ng" },
	{ name: "Egypt", code: "eg" },
	{ name: "Kenya", code: "ke" },
	{ name: "Ethiopia", code: "et" },
	{ name: "Ghana", code: "gh" },
	{ name: "Morocco", code: "ma" },
	{ name: "Algeria", code: "dz" },
	{ name: "Tunisia", code: "tn" },
	{ name: "Libya", code: "ly" },
	{ name: "Sudan", code: "sd" },
	{ name: "South Sudan", code: "ss" },
	{ name: "Senegal", code: "sn" },
	{ name: "Tanzania", code: "tz" },
	{ name: "Uganda", code: "ug" },
	{ name: "Rwanda", code: "rw" },
	{ name: "Cameroon", code: "cm" },
	{ name: "Ivory Coast", code: "ci" },
	{ name: "Angola", code: "ao" },
	{ name: "Zambia", code: "zm" },
	{ name: "Zimbabwe", code: "zw" },
	{ name: "Namibia", code: "na" },
	{ name: "Botswana", code: "bw" },
	{ name: "Madagascar", code: "mg" },
	{ name: "Mali", code: "ml" },
	{ name: "Somalia", code: "so" },
	{ name: "Mozambique", code: "mz" },
	{ name: "Mauritius", code: "mu" },
	{ name: "Seychelles", code: "sc" },
	{ name: "Cape Verde", code: "cv" },
	{ name: "Comoros", code: "km" },
	{ name: "São Tomé and Príncipe", code: "st" },
	{ name: "Democratic Republic of the Congo", code: "cd" },
	{ name: "Republic of the Congo", code: "cg" },
	{ name: "Gabon", code: "ga" },
	{ name: "Equatorial Guinea", code: "gq" },
	{ name: "Central African Republic", code: "cf" },
	{ name: "Chad", code: "td" },
	{ name: "Niger", code: "ne" },
	{ name: "Burkina Faso", code: "bf" },
	{ name: "Benin", code: "bj" },
	{ name: "Togo", code: "tg" },
	{ name: "Sierra Leone", code: "sl" },
	{ name: "Liberia", code: "lr" },
	{ name: "Guinea", code: "gn" },
	{ name: "Guinea-Bissau", code: "gw" },
	{ name: "Gambia", code: "gm" },
	{ name: "Mauritania", code: "mr" },
	{ name: "Western Sahara", code: "eh" },
	{ name: "Eritrea", code: "er" },
	{ name: "Djibouti", code: "dj" },
	{ name: "Malawi", code: "mw" },
	{ name: "Burundi", code: "bi" },
	{ name: "Lesotho", code: "ls" },
	{ name: "Eswatini", code: "sz" },
	{ name: "Réunion", code: "re" },
	{ name: "Australia", code: "au" },
	{ name: "New Zealand", code: "nz" },
	{ name: "Fiji", code: "fj" },
	{ name: "Papua New Guinea", code: "pg" },
	{ name: "Samoa", code: "ws" },
	{ name: "Tonga", code: "to" },
	{ name: "Solomon Islands", code: "sb" },
	{ name: "Vanuatu", code: "vu" },
	{ name: "Micronesia", code: "fm" },
	{ name: "Marshall Islands", code: "mh" },
	{ name: "Palau", code: "pw" },
	{ name: "Kiribati", code: "ki" },
	{ name: "Tuvalu", code: "tv" },
	{ name: "Nauru", code: "nr" },
	{ name: "Cook Islands", code: "ck" },
	{ name: "Niue", code: "nu" },
	{ name: "Tokelau", code: "tk" },
	{ name: "French Polynesia", code: "pf" },
	{ name: "New Caledonia", code: "nc" },
	{ name: "Guam", code: "gu" },
	{ name: "Northern Mariana Islands", code: "mp" },
	{ name: "American Samoa", code: "as" },
	{ name: "Wallis and Futuna", code: "wf" },
	{ name: "Cocos Island", code: "cc" },
	{ name: "Pitcairn Islands", code: "pn" },
]
	.map((flag) => ({
		...flag,
		imageUrl: `https://flagcdn.com/w320/${flag.code.toLowerCase()}.png`,
	}))
	.concat([
		{
			name: "Culture Connection",
			code: "culture_connection",
			imageUrl:
				"https://api2.cultureconnection.se/assets/achievements-frame/website/115f93a1-a1f7-4369-91a6-9107eac5feb1.png",
		},
	]);

export const getRandomOptions = (correctFlag, allFlags, count = 2) => {
	const options = [correctFlag];

	while (options.length < count) {
		const randomFlag = allFlags[Math.floor(Math.random() * allFlags.length)];
		const alreadyExists = options.some((f) => f.name === randomFlag.name);

		if (!alreadyExists) {
			options.push(randomFlag);
		}
	}

	return options.sort(() => Math.random() - 0.5);
};

export const getRandomFlag = (allFlags) => {
	if (!allFlags || allFlags.length === 0) {
		console.error("getRandomFlag called with empty or no flags array!");
		return null;
	}
	return allFlags[Math.floor(Math.random() * allFlags.length)];
};
